# Generated by Django 4.0.4 on 2022-08-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv_proj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='genalogPrototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documentos', models.IntegerField(max_length=50)),
                ('template', models.CharField(max_length=50)),
                ('text_font', models.CharField(max_length=50)),
                ('font_color', models.CharField(max_length=50)),
            ],
        ),
    ]
